test auto merge with existed tag

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -55,6 +55,23 @@ jobs:
         env:
           github_ref_type: ${{ github.ref_type }}
 
+      - name: Validate artifacts
+        run: |
+          chmod +x .github/workflows/validate_version.sh
+          ARTIFACT_DIR=target
+          LATEST_JAR=$(find "$ARTIFACT_DIR" -type f -name "*.jar" -printf "%T@ %p\n" | sort -n | tail -1 | awk '{print $2}')
+          if [ -z "$LATEST_JAR" ]; then
+            echo "Error: No JAR files found in $ARTIFACT_DIR."
+            exit 1
+          fi
+          
+          echo "Found latest JAR: $LATEST_JAR"
+          FILE_NAME=$(basename "$LATEST_JAR")
+          VERSION=$(echo "$FILE_NAME" | sed -n 's/^diadocsdk-\([0-9.]\+\(-[a-zA-Z0-9.]\+\)*\)\.jar$/\1/p')
+          echo "Validating version: $VERSION"
+          ./validate_version.sh "$VERSION"
+        
+
       - name: Upload artifacts
         uses: actions/upload-artifact@v3
         with:
@@ -63,20 +80,6 @@ jobs:
             target/*.jar
           if-no-files-found: error
 
-      - name: Validate artifacts
-        run: |
-          chmod +x validate_version.sh
-          ARTIFACT_DIR=target
-
-          for jar in $ARTIFACT_DIR/*.jar; do
-            FILE_NAME=$(basename "$jar")
-            VERSION=$(echo "$FILE_NAME" | sed -n 's/^diadocsdk-\([0-9.]\+\(-[a-zA-Z0-9.]\+\)*\)\.jar$/\1/p')
-            ./validate_version.sh "$VERSION"
-          
-          done
-
-          echo "All artifacts passed validation." 
-  
 
   publish-auto:
     runs-on: ubuntu-22.04
@@ -96,16 +99,19 @@ jobs:
         id: extract-version
         run: |
           ARTIFACT_DIR="/home/runner/work/diadocsdk-java/diadocsdk-java"
-          JAR_FILES=$(find "$ARTIFACT_DIR" -type f -name "*.jar")
-          for jar in $JAR_FILES; do
-            FILE_NAME=$(basename "$jar")
-            VERSION=$(echo "$FILE_NAME" | sed -n 's/^diadocsdk-\([0-9.]\+\(-[a-zA-Z0-9.]\+\)*\)\.jar$/\1/p')
-            if [ -n "$VERSION" ]; then
+          JAR_FILE=$(find "$ARTIFACT_DIR" -type f -name "*.jar" |  sort -n | tail -1 | awk '{print $2}')
+          if [ -z "$LATEST_JAR" ]; then
+            echo "Error: No JAR files found in $ARTIFACT_DIR."
+            exit 1
+          fi
+          echo "Found latest JAR: $LATEST_JAR"
+          FILE_NAME=$(basename "$LATEST_JAR")
+          VERSION=$(echo "$FILE_NAME" | sed -n 's/^diadocsdk-\([0-9.]\+\(-[a-zA-Z0-9.]\+\)*\)\.jar$/\1/p')
+          if [ -n "$VERSION" ]; then
               echo "VERSION=$VERSION" >> $GITHUB_ENV
-            else
-              echo "WARNING: Could not extract version from $FILE_NAME"
-            fi
-          done
+          else
+            echo "WARNING: Could not extract version from $FILE_NAME"
+          fi         
 
       - name: Create Git tag
         run: |
@@ -137,34 +143,27 @@ jobs:
         with:
           fetch-depth: 0
 
+      - name: Check versions
+        run: |
+          ARTIFACT_DIR="/home/runner/work/diadocsdk-java/diadocsdk-java"
+          JAR_FILE=$(find "$ARTIFACT_DIR" -type f -name "*.jar" |  sort -n | tail -1 | awk '{print $2}')
+          if [ -z "$LATEST_JAR" ]; then
+            echo "Error: No JAR files found in $ARTIFACT_DIR."
+            exit 1
+          fi
+          echo "Found latest JAR: $LATEST_JAR"
+          FILE_NAME=$(basename "$LATEST_JAR")
+          MANIFEST_VErSION=$(echo "$FILE_NAME" | sed -n 's/^diadocsdk-\([0-9.]\+\(-[a-zA-Z0-9.]\+\)*\)\.jar$/\1/p')
+
+          if [ "$MANIFEST_VERSION" != "$VERSION" ]; then
+              echo "Version mismatch! Jar version ($MANIFEST_VERSION) does not match tag version ($VERSION)"
+              exit 1
+          fi
+
       - name: Download artifacts
         uses: actions/download-artifact@v3
         with:
           name: packages
-
-      - name: Validate tag version
-        run: |
-          chmod +x validate_version.sh
-          TAG="${{ github.ref }}"
-          VERSION=$(echo "$TAG" | sed -n 's|.*/versions/\([0-9a-zA-Z.-]*\)|\1|p')
-          echo "Extracted version: ${VERSION}"
-          ./validate_version.sh "$VERSION"
-          
-          ARTIFACT_DIR="/home/runner/work/diadocsdk-java/diadocsdk-java"
-          JAR_FILES=$(find "$ARTIFACT_DIR" -type f -name "*.jar")
-          for jar in $JAR_FILES; do
-            FILE_NAME=$(basename "$jar")
-            MANIFEST_VERSION=$(echo "$FILE_NAME" | sed -n 's/^diadocsdk-\([0-9.]\+\(-[a-zA-Z0-9.]\+\)*\)\.jar$/\1/p')
-            if [ -n "MANIFEST_VERSION" ]; then
-              echo "MANIFEST_VERSION=$MANIFEST_VERSION" >> $GITHUB_ENV
-              if [ "$MANIFEST_VERSION" != "$VERSION" ]; then
-              echo "Version mismatch! Jar version ($MANIFEST_VERSION) does not match tag version ($VERSION)"
-              exit 1
-            fi
-            else
-              echo "WARNING: Could not extract version from $FILE_NAME"
-            fi
-          done
 
       - name: Create github release
         uses: softprops/action-gh-release@v1
