разные версии в тэге и помнике

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -77,9 +77,59 @@ jobs:
 
           echo "All artifacts passed validation."
  
-  
 
-  publish:
+  publish-auto:
+    runs-on: ubuntu-22.04
+    needs: build
+    if: github.ref == 'refs/heads/master'
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+
+      - name: Extract JAR version
+        id: extract-version
+        run: |
+          ARTIFACT_DIR=target
+          VERSION=""
+          for jar in $ARTIFACT_DIR/*.jar; do
+            FILE_NAME=$(basename "$jar")
+            VERSION=$(echo "$FILE_NAME" | sed -n 's/^diadocsdk-\([0-9.]\+\(-[a-zA-Z0-9.]\+\)*\)\.jar$/\1/p')
+            if [ -z "$VERSION" ]; then
+              echo "Failed to extract version from $FILE_NAME"
+              exit 1
+            fi
+          done
+          echo "::set-output name=version::$VERSION"
+        env:
+          ARTIFACT_DIR: target
+
+      - name: Create Git tag
+        run: |
+          git config user.name "github-actions[bot]"
+          git config user.email "github-actions[bot]@users.noreply.github.com"
+          git tag versions/${{ steps.extract-version.outputs.version }}
+          git push origin versions/${{ steps.extract-version.outputs.version }}
+
+      - name: Download artifacts
+        uses: actions/download-artifact@v3
+        with:
+          name: packages
+
+      - name: Create GitHub release
+        uses: softprops/action-gh-release@v1
+        with:
+          fail_on_unmatched_files: true
+          draft: false
+          prerelease: false
+          files: |
+            **/*.jar
+          tag_name: versions/${{ steps.extract-version.outputs.version }}
+          name: Release ${{ steps.extract-version.outputs.version }}
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+  publish-manual:
     runs-on: ubuntu-22.04
     needs: build
     if: |
