fix

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -65,42 +65,26 @@ jobs:
 
       - name: Validate artifacts
         run: |
-          VERSION_REGEX='^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-(0|[1-9][0-9]*|[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9][0-9]*|[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$'
+          chmod +x validate_version.sh
           ARTIFACT_DIR=target
-      
+
           for jar in $ARTIFACT_DIR/*.jar; do
             FILE_NAME=$(basename "$jar")
-            if [[ ! "$FILE_NAME" =~ ^diadocsdk ]]; then
+
+            if [[ "$FILE_NAME" =~ ^diadocsdk ]]; then
               echo "Skipping file $FILE_NAME: does not start with 'diadocsdk'"
-              continue
-            fi         
-          
-            VERSION=$(echo "$FILE_NAME" | grep -oP '(?<=diadocsdk-)[^-]+(?:-[^\.]+)?(?=\.jar)')
-            if [[ -z "$VERSION" ]]; then
-              echo "Error: Failed to extract version from $FILE_NAME"
-              exit 1
+              VERSION=$(echo "$FILE_NAME" | grep -oP '(?<=diadocsdk-)[^-]+(?:-[^\.]+)?(?=\.jar)')
+              if [[ -z "$VERSION" ]]; then
+                echo "Error: Failed to extract version from $FILE_NAME"
+                exit 1
+              fi
+              ./validate_version.sh "$VERSION"
+              break
             fi
-      
-            MATCH_RESULT=$(echo "$VERSION" | awk -v regex="$VERSION_REGEX" '
-            BEGIN { result=1 }
-            {
-              if (match($0, regex)) {
-                result=0
-              } else {
-                print "Error: Artifact " $0 " does not match the version regex " regex
-              }
-            }
-            END { exit result }
-            ')
-            if [ $? -ne 0 ]; then
-              echo "$MATCH_RESULT"
-            fi
-      
-            echo "Artifact $FILE_NAME with version $VERSION matches the regex."
           done
-      
-          echo "All artifacts match the version regex."
-  
+
+          echo "All artifacts passed validation."
+ 
   
 
   publish:
@@ -115,25 +99,12 @@ jobs:
 
       - name: Validate tag version
         run: |
+          chmod +x validate_version.sh
           TAG="${{ github.ref }}"
-          TAG="${TAG#refs/tags/}"
-          echo "Extracted tag: ${TAG}"
+          VERSION="${TAG#refs/tags/}"
+          echo "Extracted version: ${VERSION}"
           VERSION_REGEX='^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-(0|[1-9][0-9]*|[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9][0-9]*|[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$'
-          MATCH_RESULT=$(echo "$TAG" | awk -v regex="$VERSION_REGEX" '
-            BEGIN { result=1 }
-            {
-              if (match($0, regex)) {
-              result=0
-            } else {
-              print "Error: Artifact " $0 " does not match the version regex " regex
-            }
-            }
-            END { exit result }
-            ')       
-            if [ $? -ne 0 ]; then
-              echo "$MATCH_RESULT"
-              exit 1
-            fi  
+          ./validate_version.sh "$VERSION"
 
       - name: Download artifacts
         uses: actions/download-artifact@v3
